### ISSUE TITLE
a2ensite not working correctly

### ISSUE THREAD

**Issue by Krutonium** [TsPG128/arch-a2ensite-a2dissite#1]
krutonium@resindrakenet  /etc/httpd/conf  sudo a2ensite www.resindrake.net.conf
[*] Linked the site www.resindrake.net.conf.
[!] Syntax check failed!
[!] Please run 'apachectl -f /etc/httpd/conf/httpd.conf -t' and investigate.
[!] Removing the link and exiting...
 ✘ krutonium@resindrakenet  /etc/httpd/conf  apachectl -f /etc/httpd/conf/httpd.conf -t
Syntax OK

**Comment by TsPG128** [comment]
Hi there, thank you for your contribution.
I'm assuming the www.resindrake.net.conf file has errors in it. As the a2ensite script unlinks the configuration file on errors, the standard test won't apply to your vhost file.

Please link your configuration file manually and rerun the test:
```
sudo ln -s /etc/httpd/conf/sites-available/www.resindrake.net.conf /etc/httpd/conf/sites-enabled/www.resindrake.net.conf
apachectl -f /etc/httpd/conf/httpd.conf -t
```

**Comment by Krutonium** [comment]
Yeah, sorry, I was frustrated, I'm in the middle of migrating a bunch of sites and I lost my head a little. I've since fixed it, sorry for bothering.

You were right by the way.
